### ISSUE TITLE
Mover prettier to dependencies vs. devDependencies

### ISSUE THREAD

**Issue by humphd** [MizuhoOkimoto/pajama-ssg#11]
Often we put `prettier` in the `devDependencies` of `package.json`, because we only use it to format files during development.  However, since you are [using it in your runtime code](https://github.com/MizuhoOkimoto/pajama-ssg/blob/main/pajama-ssg/pajama-ssg.js#L13), you need to include it in `dependencies`.  This is important because people often install only the `dependencies` vs. `devDependencies` when using vs. developing a project, and your code will break without `prettier`.

**Comment by MizuhoOkimoto** [comment]
I didn't know about "devDependencies" and Prettier went inside there without my intention. Thank you for checking the details!
