### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by humphd** [MizuhoOkimoto/pajama-ssg#13]
You are dealing with errors by either logging the error or throwing.  In both cases, the user will be confronted with an error they don't understand.  A better way is to print a helpful error message, and then exit the program with an error code:

```js
if(err) {
  console.error('Helpful error message...');
  // If this is fatal, exit now with non-zero result code
  process.exit(-1);
}
```

**Comment by MizuhoOkimoto** [comment]
I changed them to helpful messages. Thank you for your advice!
