### ISSUE TITLE
Could any info be added to help improve the documentation?

### ISSUE THREAD

**Issue by aserputov** [MizuhoOkimoto/pajama-ssg#2]
Yes, I got this problem after I tried to use $npm i -g . I'm not really sure if that's a mistake, but I got this error.
<img width="692" alt="Screen Shot 2021-09-16 at 11 37 19 PM" src="https://user-images.githubusercontent.com/65831678/133848738-49b6b6d4-31d2-4d2b-8303-9935852351ec.png">

**Comment by MizuhoOkimoto** [comment]
I found my program didn't need the command for installation. I delete it on my README.md. Thank you for pointing it out.
