### ISSUE TITLE
 Is it valid? Test it at https://html5.validator.nu/ 

### ISSUE THREAD

**Issue by aserputov** [MizuhoOkimoto/pajama-ssg#6]
I tested and got errors(attached as a photo)
<img width="2148" alt="Screen Shot 2021-09-17 at 12 24 06 AM" src="https://user-images.githubusercontent.com/65831678/133849254-8918b687-c4bb-4014-b248-bdb5b9b2a4ef.png">

**Comment by MizuhoOkimoto** [comment]
The cause was that I added spaces to the CSS path. I fixed it and it became validated! Thank you!
![image](https://user-images.githubusercontent.com/54873998/133873725-8aad436b-0be2-4614-ac17-022d4c5b0282.png)
